//! This code was AUTOGENERATED using the Codama library.
pub mod cpi_event_row;
pub mod initialize_protocol_fee_row;
pub mod swap_row;
pub mod update_protocol_fee_row;

pub use self::{
    cpi_event_row::*, initialize_protocol_fee_row::*, swap_row::*, update_protocol_fee_row::*,
};
use super::ZapInstruction;

pub struct ZapInstructionsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for ZapInstructionsMigration {
    fn app(&self) -> &str {
        "zap"
    }

    fn name(&self) -> &str {
        "zap_instructions"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(InitializeProtocolFeeMigrationOperation),
            Box::new(SwapMigrationOperation),
            Box::new(UpdateProtocolFeeMigrationOperation),
            Box::new(CpiEventMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct ZapInstructionWithMetadata(
    pub ZapInstruction,
    pub carbon_core::instruction::InstructionMetadata,
    pub Vec<solana_instruction::AccountMeta>,
);

impl
    From<(
        ZapInstruction,
        carbon_core::instruction::InstructionMetadata,
        Vec<solana_instruction::AccountMeta>,
    )> for ZapInstructionWithMetadata
{
    fn from(
        value: (
            ZapInstruction,
            carbon_core::instruction::InstructionMetadata,
            Vec<solana_instruction::AccountMeta>,
        ),
    ) -> Self {
        ZapInstructionWithMetadata(value.0, value.1, value.2)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for ZapInstructionWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let ZapInstructionWithMetadata(decoded_instruction, metadata, raw_accounts) = self;
        match decoded_instruction {
            ZapInstruction::InitializeProtocolFee { data, .. } => {
                let row = initialize_protocol_fee_row::InitializeProtocolFeeRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            ZapInstruction::Swap { data, .. } => {
                let row = swap_row::SwapRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            ZapInstruction::UpdateProtocolFee { data, .. } => {
                let row = update_protocol_fee_row::UpdateProtocolFeeRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            ZapInstruction::CpiEvent { data, .. } => {
                let row = cpi_event_row::CpiEventRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for ZapInstructionWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let ZapInstructionWithMetadata(decoded_instruction, metadata, raw_accounts) = self;
        match decoded_instruction {
            ZapInstruction::InitializeProtocolFee { data, .. } => {
                let row = initialize_protocol_fee_row::InitializeProtocolFeeRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            ZapInstruction::Swap { data, .. } => {
                let row = swap_row::SwapRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            ZapInstruction::UpdateProtocolFee { data, .. } => {
                let row = update_protocol_fee_row::UpdateProtocolFeeRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            ZapInstruction::CpiEvent { data, .. } => {
                let row = cpi_event_row::CpiEventRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
