//! This code was AUTOGENERATED using the Codama library.
pub mod cpi_event_row;
pub mod initialize_protocol_fee_row;
pub mod swap_row;
pub mod update_protocol_fee_row;

pub use self::{
    cpi_event_row::*, initialize_protocol_fee_row::*, swap_row::*, update_protocol_fee_row::*,
};
use super::ZapInstruction;

pub struct ZapInstructionsMigration;

impl carbon_core::clickhouse::Migration for ZapInstructionsMigration {
    fn app(&self) -> &str {
        "zap"
    }
    fn name(&self) -> &str {
        "zap_instructions"
    }
    fn operations(&self) -> Vec<Box<dyn carbon_core::clickhouse::operations::Operation>> {
        vec![
            Box::new(InitializeProtocolFeeMigrationOperation),
            Box::new(SwapMigrationOperation),
            Box::new(UpdateProtocolFeeMigrationOperation),
            Box::new(CpiEventMigrationOperation),
        ]
    }
}

pub enum ZapInstructionRow {
    InitializeProtocolFee(InitializeProtocolFeeRow),
    Swap(SwapRow),
    UpdateProtocolFee(UpdateProtocolFeeRow),
    CpiEvent(CpiEventRow),
}

pub struct ZapInstructionMetadata<'a>(
    pub &'a carbon_core::instruction::InstructionMetadata,
    pub &'a ZapInstruction,
);

impl<'a> carbon_core::clickhouse::BatchInsert for ZapInstructionMetadata<'a> {
    type Row = ZapInstructionRow;

    fn batch_insert(&self, rows: &mut Vec<Self::Row>) -> carbon_core::error::CarbonResult<()> {
        let &Self(metadata, instruction) = self;

        macro_rules! insert_branch {
            ($variant:ident, $row:ty) => {
                if let ZapInstruction::$variant { data, accounts, .. } = instruction {
                    rows.push(ZapInstructionRow::$variant(<$row>::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?));
                    return Ok(());
                }
            };
        }

        insert_branch!(InitializeProtocolFee, InitializeProtocolFeeRow);
        insert_branch!(Swap, SwapRow);
        insert_branch!(UpdateProtocolFee, UpdateProtocolFeeRow);
        insert_branch!(CpiEvent, CpiEventRow);
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::clickhouse::BatchCommit for ZapInstructionRow {
    async fn batch_commit(
        client: &clickhouse::Client,
        rows: &[Self],
    ) -> carbon_core::error::CarbonResult<()> {
        macro_rules! commit_branch {
            ($variant:ident, $row:ty) => {{
                let branch_rows: Vec<$row> = rows
                    .iter()
                    .filter_map(|row| match row {
                        Self::$variant(row) => Some(row.clone()),
                        _ => None,
                    })
                    .collect();

                if !branch_rows.is_empty() {
                    <$row as carbon_core::clickhouse::Insert>::insert(client, &branch_rows).await?;
                }
            }};
        }

        commit_branch!(InitializeProtocolFee, InitializeProtocolFeeRow);
        commit_branch!(Swap, SwapRow);
        commit_branch!(UpdateProtocolFee, UpdateProtocolFeeRow);
        commit_branch!(CpiEvent, CpiEventRow);
        Ok(())
    }
}
