//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::deserialize::CarbonDeserialize, solana_pubkey::Pubkey};

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct SwapCompletedEventEvent {
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub mint0: Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub mint1: Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub from: Pubkey,
    pub amount0: u64,
    pub amount1: u64,
    pub mint0_decimals: u8,
    pub mint1_decimals: u8,
    pub zero_for_one: bool,
}

impl CarbonDeserialize for SwapCompletedEventEvent {
    const DISCRIMINATOR: &'static [u8] = &[91, 116, 215, 245, 243, 199, 17, 180];

    fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != Self::DISCRIMINATOR {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
