//! This code was AUTOGENERATED using the Codama library.
#[cfg(feature = "graphql")]
pub mod graphql;

pub mod collect_protocol_fee_event;
pub mod collect_user_fee_event;
pub mod fee_config;
pub mod fee_share;
pub mod protocol_fee_parameters;
pub mod swap_completed_event;
pub mod swap_params;

pub use self::{
    collect_protocol_fee_event::*, collect_user_fee_event::*, fee_config::*, fee_share::*,
    protocol_fee_parameters::*, swap_completed_event::*, swap_params::*,
};
