//! This code was AUTOGENERATED using the Codama library.
use crate::types::FeeConfig;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct SwapParams {
    pub data: Vec<u8>,
    pub fee_config: Option<FeeConfig>,
    pub protocol_fee: Option<u16>,
}
