//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct SwapCompletedEvent {
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub mint0: Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub mint1: Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub from: Pubkey,
    pub amount0: u64,
    pub amount1: u64,
    pub mint0_decimals: u8,
    pub mint1_decimals: u8,
    pub zero_for_one: bool,
}
