//! This code was AUTOGENERATED using the Codama library.
pub mod protocol_fee_row;

pub use self::protocol_fee_row::*;
use super::ZapAccount;

pub struct ZapAccountsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for ZapAccountsMigration {
    fn app(&self) -> &str {
        "zap"
    }

    fn name(&self) -> &str {
        "zap_accounts"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![Box::new(ProtocolFeeMigrationOperation)]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct ZapAccountWithMetadata(pub ZapAccount, pub carbon_core::account::AccountMetadata);

impl From<(ZapAccount, carbon_core::account::AccountMetadata)> for ZapAccountWithMetadata {
    fn from(value: (ZapAccount, carbon_core::account::AccountMetadata)) -> Self {
        ZapAccountWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for ZapAccountWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let ZapAccountWithMetadata(account, metadata) = self;

        match account {
            ZapAccount::ProtocolFee(account) => {
                let row = protocol_fee_row::ProtocolFeeRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for ZapAccountWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let ZapAccountWithMetadata(account, metadata) = self;
        match account {
            ZapAccount::ProtocolFee(account) => {
                let row = protocol_fee_row::ProtocolFeeRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
