//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    account::AccountMetadata,
    postgres::{
        metadata::AccountRowMetadata,
        primitives::{Pubkey, U16, U8},
    },
};

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct ProtocolFeeRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub bump: U8,
    pub padding: Vec<u8>,
    pub fee_bps: U16,
    pub protocol_vault: Pubkey,
}

impl ProtocolFeeRow {
    pub fn from_parts(
        source: crate::accounts::protocol_fee::ProtocolFee,
        metadata: AccountMetadata,
    ) -> Self {
        Self {
            account_metadata: metadata.into(),
            bump: source.bump.into(),
            padding: source.padding.to_vec(),
            fee_bps: source.fee_bps.into(),
            protocol_vault: source.protocol_vault.into(),
        }
    }
}

impl TryFrom<ProtocolFeeRow> for crate::accounts::protocol_fee::ProtocolFee {
    type Error = carbon_core::error::Error;
    fn try_from(source: ProtocolFeeRow) -> Result<Self, Self::Error> {
        Ok(Self {
            bump: source.bump.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            padding: source.padding.as_slice().try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert padding from postgres primitive: expected 7 bytes"
                        .to_string(),
                )
            })?,
            fee_bps: source.fee_bps.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            protocol_vault: *source.protocol_vault,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::protocol_fee::ProtocolFee {
    fn table() -> &'static str {
        "zap_protocol_fee_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "bump",
            "padding",
            "fee_bps",
            "protocol_vault",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for ProtocolFeeRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO zap_protocol_fee_account (
                "bump",
                "padding",
                "fee_bps",
                "protocol_vault",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6
            )"#,
        )
        .bind(self.bump)
        .bind(&self.padding)
        .bind(self.fee_bps)
        .bind(self.protocol_vault)
        .bind(self.account_metadata.pubkey)
        .bind(&self.account_metadata.slot)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for ProtocolFeeRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO zap_protocol_fee_account (
                "bump",
                "padding",
                "fee_bps",
                "protocol_vault",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "bump" = EXCLUDED."bump",
                "padding" = EXCLUDED."padding",
                "fee_bps" = EXCLUDED."fee_bps",
                "protocol_vault" = EXCLUDED."protocol_vault",
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.bump)
        .bind(&self.padding)
        .bind(self.fee_bps)
        .bind(self.protocol_vault)
        .bind(self.account_metadata.pubkey)
        .bind(&self.account_metadata.slot)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for ProtocolFeeRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM zap_protocol_fee_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Lookup for ProtocolFeeRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM zap_protocol_fee_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct ProtocolFeeMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for ProtocolFeeMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS zap_protocol_fee_account (
                -- Account data
                "bump" INT2 NOT NULL,
                "padding" BYTEA NOT NULL,
                "fee_bps" INT4 NOT NULL,
                "protocol_vault" BYTEA NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS zap_protocol_fee_account"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
