//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct ZapDecoder;
pub const PROGRAM_ID: Pubkey =
    solana_pubkey::Pubkey::from_str_const("RH1NLqLxRAUxTq3L1SBS1ED78o1fHxQqRwnBQYVsYub");

pub mod accounts;
pub mod events;
#[cfg(feature = "graphql")]
pub mod graphql;
pub mod instructions;
pub mod types;
