//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct ZapDecoder;
pub const PROGRAM_ID: Pubkey =
    solana_pubkey::Pubkey::from_str_const("RH1Kc6gvrQpruCzvw8z9k2U8tATRxkzHTej3jb9nmdA");

pub mod accounts;
pub mod events;
#[cfg(feature = "graphql")]
pub mod graphql;
pub mod instructions;
pub mod types;
