//! This code was AUTOGENERATED using the Codama library.
pub mod protocol_fee_row;

pub use self::protocol_fee_row::*;
use super::ZapAccount;

pub struct ZapAccountsMigration;

impl carbon_core::clickhouse::Migration for ZapAccountsMigration {
    fn app(&self) -> &str {
        "zap"
    }
    fn name(&self) -> &str {
        "zap_accounts"
    }
    fn operations(&self) -> Vec<Box<dyn carbon_core::clickhouse::operations::Operation>> {
        vec![Box::new(ProtocolFeeMigrationOperation)]
    }
}

pub enum ZapAccountRow {
    ProtocolFee(ProtocolFeeRow),
}

pub struct ZapAccountMetadata<'a>(
    pub &'a carbon_core::account::AccountMetadata,
    pub &'a ZapAccount,
);

impl<'a> carbon_core::clickhouse::BatchInsert for ZapAccountMetadata<'a> {
    type Row = ZapAccountRow;

    fn batch_insert(&self, rows: &mut Vec<Self::Row>) -> carbon_core::error::CarbonResult<()> {
        let &Self(metadata, account) = self;

        macro_rules! insert_branch {
            ($variant:ident, $row:ty, boxed) => {
                if let ZapAccount::$variant(account) = account {
                    rows.push(ZapAccountRow::$variant(<$row>::try_from((
                        account.as_ref().clone(),
                        metadata.clone(),
                    ))?));
                    return Ok(());
                }
            };
            ($variant:ident, $row:ty, plain) => {
                if let ZapAccount::$variant(account) = account {
                    rows.push(ZapAccountRow::$variant(<$row>::try_from((
                        account.clone(),
                        metadata.clone(),
                    ))?));
                    return Ok(());
                }
            };
        }

        insert_branch!(ProtocolFee, ProtocolFeeRow, boxed);
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::clickhouse::BatchCommit for ZapAccountRow {
    async fn batch_commit(
        client: &clickhouse::Client,
        rows: &[Self],
    ) -> carbon_core::error::CarbonResult<()> {
        macro_rules! commit_branch {
            ($variant:ident, $row:ty) => {{
                let branch_rows: Vec<$row> = rows
                    .iter()
                    .filter_map(|row| match row {
                        Self::$variant(row) => Some(row.clone()),
                        _ => None,
                    })
                    .collect();

                if !branch_rows.is_empty() {
                    <$row as carbon_core::clickhouse::Insert>::insert(client, &branch_rows).await?;
                }
            }};
        }

        commit_branch!(ProtocolFee, ProtocolFeeRow);
        Ok(())
    }
}
