//! This code was AUTOGENERATED using the Codama library.
#[derive(clickhouse::Row, serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct ProtocolFeeRow {
    pub __pubkey: String,
    pub __slot: u64,
    pub data: String,
}

impl
    TryFrom<(
        crate::accounts::protocol_fee::ProtocolFee,
        carbon_core::account::AccountMetadata,
    )> for ProtocolFeeRow
{
    type Error = carbon_core::error::Error;

    fn try_from(
        (source, metadata): (
            crate::accounts::protocol_fee::ProtocolFee,
            carbon_core::account::AccountMetadata,
        ),
    ) -> Result<Self, Self::Error> {
        let data = serde_json::to_string(&source)
            .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;

        Ok(Self {
            __pubkey: metadata.pubkey.to_string(),
            __slot: metadata.slot,
            data,
        })
    }
}

impl TryFrom<ProtocolFeeRow>
    for (
        crate::accounts::protocol_fee::ProtocolFee,
        carbon_core::account::AccountMetadata,
    )
{
    type Error = carbon_core::error::Error;

    fn try_from(value: ProtocolFeeRow) -> Result<Self, Self::Error> {
        let pubkey = value
            .__pubkey
            .parse::<solana_pubkey::Pubkey>()
            .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;
        let source: crate::accounts::protocol_fee::ProtocolFee = serde_json::from_str(&value.data)
            .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;

        Ok((
            source,
            carbon_core::account::AccountMetadata {
                slot: value.__slot,
                pubkey,
                transaction_signature: None,
            },
        ))
    }
}
#[cfg(feature = "clickhouse-cluster")]
impl carbon_core::clickhouse::ClusterTable for ProtocolFeeRow {
    fn local_table() -> &'static str {
        "zap_protocol_fee_account_local"
    }

    fn distributed_table() -> &'static str {
        "zap_protocol_fee_account"
    }
}

#[cfg(not(feature = "clickhouse-cluster"))]
impl carbon_core::clickhouse::Table for ProtocolFeeRow {
    fn table() -> &'static str {
        "zap_protocol_fee_account"
    }
}

#[async_trait::async_trait]
impl carbon_core::clickhouse::Insert for ProtocolFeeRow {
    async fn insert(
        client: &clickhouse::Client,
        rows: &[Self],
    ) -> carbon_core::error::CarbonResult<()> {
        if rows.is_empty() {
            return Ok(());
        }

        let mut insert = client
            .insert::<Self>("zap_protocol_fee_account")
            .await
            .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;

        for row in rows {
            insert
                .write(row)
                .await
                .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;
        }

        insert
            .end()
            .await
            .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;
        Ok(())
    }
}

pub struct ProtocolFeeMigrationOperation;

#[cfg(feature = "clickhouse-cluster")]
#[async_trait::async_trait]
impl carbon_core::clickhouse::Operation for ProtocolFeeMigrationOperation {
    async fn up(
        &self,
        client: &clickhouse::Client,
        config: &carbon_core::clickhouse::MigrationConfig,
    ) -> clickhouse::error::Result<()> {
        let cluster_name = &config.cluster_name;
        let replica_path = format!(
            "/clickhouse/tables/{}/zap_protocol_fee_account_local",
            config.shard_name,
        );

        client
            .query(&format!(
                r#"
                    CREATE TABLE IF NOT EXISTS zap_protocol_fee_account_local ON CLUSTER {cluster} (
                        __pubkey String,
                        __slot UInt64,
                        data String
                    )
                    ENGINE = ReplicatedReplacingMergeTree('{replica_path}', '{{replica}}')
                    ORDER BY (__pubkey)
                "#,
                cluster = cluster_name,
                replica_path = replica_path,
            ))
            .execute()
            .await?;

        client
            .query(&format!(
                r#"
                    CREATE TABLE IF NOT EXISTS zap_protocol_fee_account ON CLUSTER {cluster} AS zap_protocol_fee_account_local
                    ENGINE = Distributed({cluster}, currentDatabase(), zap_protocol_fee_account_local, rand())
                "#,
                cluster = cluster_name,
            ))
            .execute()
            .await?;

        Ok(())
    }

    async fn down(
        &self,
        client: &clickhouse::Client,
        config: &carbon_core::clickhouse::MigrationConfig,
    ) -> clickhouse::error::Result<()> {
        let cluster_name = &config.cluster_name;

        client
            .query(&format!(
                "DROP TABLE IF EXISTS zap_protocol_fee_account ON CLUSTER {cluster}",
                cluster = cluster_name,
            ))
            .execute()
            .await?;

        client
            .query(&format!(
                "DROP TABLE IF EXISTS zap_protocol_fee_account_local ON CLUSTER {cluster}",
                cluster = cluster_name,
            ))
            .execute()
            .await?;

        Ok(())
    }
}

#[cfg(not(feature = "clickhouse-cluster"))]
#[async_trait::async_trait]
impl carbon_core::clickhouse::Operation for ProtocolFeeMigrationOperation {
    async fn up(&self, client: &clickhouse::Client) -> clickhouse::error::Result<()> {
        client
            .query(
                r#"
                    CREATE TABLE IF NOT EXISTS zap_protocol_fee_account (
                        __pubkey String,
                        __slot UInt64,
                        data String
                    )
                    ENGINE = ReplacingMergeTree()
                    ORDER BY (__pubkey)
                "#,
            )
            .execute()
            .await?;

        Ok(())
    }

    async fn down(&self, client: &clickhouse::Client) -> clickhouse::error::Result<()> {
        client
            .query("DROP TABLE IF EXISTS zap_protocol_fee_account")
            .execute()
            .await?;

        Ok(())
    }
}
