//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, U64, U8},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "CollectProtocolFeeEvent")]
pub struct CollectProtocolFeeEventGraphQL {
    pub mint: Pubkey,
    pub from: Pubkey,
    pub amount: U64,
    pub decimals: U8,
}

impl From<crate::types::CollectProtocolFeeEvent> for CollectProtocolFeeEventGraphQL {
    fn from(original: crate::types::CollectProtocolFeeEvent) -> Self {
        Self {
            mint: carbon_core::graphql::primitives::Pubkey(original.mint),
            from: carbon_core::graphql::primitives::Pubkey(original.from),
            amount: carbon_core::graphql::primitives::U64(original.amount),
            decimals: carbon_core::graphql::primitives::U8(original.decimals),
        }
    }
}
