//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, U64, U8},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "CollectUserFeeEvent")]
pub struct CollectUserFeeEventGraphQL {
    pub mint: Pubkey,
    pub from: Pubkey,
    pub to: Pubkey,
    pub amount: U64,
    pub decimals: U8,
}

impl From<crate::types::CollectUserFeeEvent> for CollectUserFeeEventGraphQL {
    fn from(original: crate::types::CollectUserFeeEvent) -> Self {
        Self {
            mint: carbon_core::graphql::primitives::Pubkey(original.mint),
            from: carbon_core::graphql::primitives::Pubkey(original.from),
            to: carbon_core::graphql::primitives::Pubkey(original.to),
            amount: carbon_core::graphql::primitives::U64(original.amount),
            decimals: carbon_core::graphql::primitives::U8(original.decimals),
        }
    }
}
