//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::graphql::primitives::Pubkey, juniper::GraphQLObject};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "FeeShare")]
pub struct FeeShareGraphQL {
    pub share_bps: i32,
    pub address: Pubkey,
}

impl From<crate::types::FeeShare> for FeeShareGraphQL {
    fn from(original: crate::types::FeeShare) -> Self {
        Self {
            share_bps: original.share_bps as i32,
            address: carbon_core::graphql::primitives::Pubkey(original.address),
        }
    }
}
