//! This code was AUTOGENERATED using the Codama library.
use {crate::types::graphql::FeeShareGraphQL, juniper::GraphQLObject};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "FeeConfig")]
pub struct FeeConfigGraphQL {
    pub user_fee_share_bps: i32,
    pub user_fee_shares: Vec<FeeShareGraphQL>,
}

impl From<crate::types::FeeConfig> for FeeConfigGraphQL {
    fn from(original: crate::types::FeeConfig) -> Self {
        Self {
            user_fee_share_bps: original.user_fee_share_bps as i32,
            user_fee_shares: original
                .user_fee_shares
                .into_iter()
                .map(|item| item.into())
                .collect(),
        }
    }
}
