//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::graphql::primitives::Pubkey, juniper::GraphQLObject};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ProtocolFeeParameters")]
pub struct ProtocolFeeParametersGraphQL {
    pub protocol_vault: Pubkey,
}

impl From<crate::types::ProtocolFeeParameters> for ProtocolFeeParametersGraphQL {
    fn from(original: crate::types::ProtocolFeeParameters) -> Self {
        Self {
            protocol_vault: carbon_core::graphql::primitives::Pubkey(original.protocol_vault),
        }
    }
}
