//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, U64, U8},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "SwapCompletedEvent")]
pub struct SwapCompletedEventGraphQL {
    pub mint0: Pubkey,
    pub mint1: Pubkey,
    pub from: Pubkey,
    pub amount0: U64,
    pub amount1: U64,
    pub mint0_decimals: U8,
    pub mint1_decimals: U8,
    pub zero_for_one: bool,
}

impl From<crate::types::SwapCompletedEvent> for SwapCompletedEventGraphQL {
    fn from(original: crate::types::SwapCompletedEvent) -> Self {
        Self {
            mint0: carbon_core::graphql::primitives::Pubkey(original.mint0),
            mint1: carbon_core::graphql::primitives::Pubkey(original.mint1),
            from: carbon_core::graphql::primitives::Pubkey(original.from),
            amount0: carbon_core::graphql::primitives::U64(original.amount0),
            amount1: carbon_core::graphql::primitives::U64(original.amount1),
            mint0_decimals: carbon_core::graphql::primitives::U8(original.mint0_decimals),
            mint1_decimals: carbon_core::graphql::primitives::U8(original.mint1_decimals),
            zero_for_one: original.zero_for_one,
        }
    }
}
