//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::graphql::FeeConfigGraphQL, carbon_core::graphql::primitives::U8,
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "SwapParams")]
pub struct SwapParamsGraphQL {
    pub data: Vec<U8>,
    pub fee_config: Option<FeeConfigGraphQL>,
}

impl From<crate::types::SwapParams> for SwapParamsGraphQL {
    fn from(original: crate::types::SwapParams) -> Self {
        Self {
            data: original
                .data
                .into_iter()
                .map(carbon_core::graphql::primitives::U8)
                .collect(),
            fee_config: original.fee_config.map(|v| v.into()),
        }
    }
}
