//! This code was AUTOGENERATED using the Codama library.
use crate::{ZapDecoder, PROGRAM_ID};

#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "clickhouse")]
pub mod clickhouse;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod cpi_event;
pub mod initialize_protocol_fee;
pub mod swap;
pub mod update_protocol_fee;

pub use self::{cpi_event::*, initialize_protocol_fee::*, swap::*, update_protocol_fee::*};

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
#[cfg_attr(feature = "serde", derive(carbon_core::InstructionType))]
pub enum ZapInstruction {
    InitializeProtocolFee {
        #[cfg_attr(
            feature = "base58",
            serde(serialize_with = "carbon_core::convert::base58::serialize")
        )]
        program_id: solana_pubkey::Pubkey,
        data: InitializeProtocolFee,
        accounts: InitializeProtocolFeeInstructionAccounts,
    },
    Swap {
        #[cfg_attr(
            feature = "base58",
            serde(serialize_with = "carbon_core::convert::base58::serialize")
        )]
        program_id: solana_pubkey::Pubkey,
        data: Swap,
        accounts: SwapInstructionAccounts,
    },
    UpdateProtocolFee {
        #[cfg_attr(
            feature = "base58",
            serde(serialize_with = "carbon_core::convert::base58::serialize")
        )]
        program_id: solana_pubkey::Pubkey,
        data: UpdateProtocolFee,
        accounts: UpdateProtocolFeeInstructionAccounts,
    },
    CpiEvent {
        #[cfg_attr(
            feature = "base58",
            serde(serialize_with = "carbon_core::convert::base58::serialize")
        )]
        program_id: solana_pubkey::Pubkey,
        data: CpiEvent,
        accounts: CpiEventInstructionAccounts,
    },
}

impl carbon_core::instruction::InstructionDecoder<'_> for ZapDecoder {
    type InstructionType = ZapInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<Self::InstructionType> {
        if instruction.program_id != PROGRAM_ID {
            return None;
        }

        carbon_core::try_decode_instructions!(
            instruction,
            PROGRAM_ID,
            ZapInstruction::InitializeProtocolFee => InitializeProtocolFee,
            ZapInstruction::Swap => Swap,
            ZapInstruction::UpdateProtocolFee => UpdateProtocolFee,
            ZapInstruction::CpiEvent => CpiEvent,
        )
    }
}
