//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::ProtocolFeeParameters,
    carbon_core::{
        account_utils::next_account,
        deserialize::{ArrangeAccounts, CarbonDeserialize},
    },
};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct UpdateProtocolFee {
    pub params: ProtocolFeeParameters,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateProtocolFeeInstructionAccounts {
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub protocol_fee: solana_pubkey::Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub owner: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CarbonDeserialize for UpdateProtocolFee {
    const DISCRIMINATOR: &'static [u8] = &[170, 136, 6, 60, 43, 130, 81, 96];

    fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != Self::DISCRIMINATOR {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for UpdateProtocolFee {
    type ArrangedAccounts = UpdateProtocolFeeInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let protocol_fee = next_account(&mut iter)?;
        let owner = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(UpdateProtocolFeeInstructionAccounts {
            protocol_fee,
            owner,
            remaining: remaining.to_vec(),
        })
    }
}
